### ISSUE TITLE
template path error

### ISSUE THREAD

**Issue by jkobject** [grst/ipymd#25]
```bash
Error while saving file: copy_number.Rmd ../ressources/r_notebook.template.html
    Traceback (most recent call last):
      File "/home/jeremie/miniconda3/lib/python3.7/site-packages/ipymd/core/contents_manager.py", line 155, in save
        to=self.format)
      File "/home/jeremie/miniconda3/lib/python3.7/site-packages/ipymd/core/format_manager.py", line 349, in convert
        return format_manager().convert(*args, **kwargs)
      File "/home/jeremie/miniconda3/lib/python3.7/site-packages/ipymd/core/format_manager.py", line 266, in convert
        return convert_rmarkdown(from_, to, contents)
      File "/home/jeremie/miniconda3/lib/python3.7/site-packages/ipymd/core/format_manager.py", line 357, in convert_rmarkdown
        return writer.contents
      File "/home/jeremie/miniconda3/lib/python3.7/site-packages/ipymd/formats/rmarkdown.py", line 278, in contents
        'html': self.nb_html_writer.contents
      File "/home/jeremie/miniconda3/lib/python3.7/site-packages/ipymd/formats/rmarkdown.py", line 537, in contents
        return self.template.render(filename=filename,
      File "/home/jeremie/miniconda3/lib/python3.7/site-packages/ipymd/formats/rmarkdown.py", line 365, in template
        return env.get_template('../ressources/r_notebook.template.html')
      File "/home/jeremie/miniconda3/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
        return self._load_template(name, self.make_globals(globals))
      File "/home/jeremie/miniconda3/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
        template = self.loader.load(self, name, globals)
      File "/home/jeremie/miniconda3/lib/python3.7/site-packages/jinja2/loaders.py", line 113, in load
        source, filename, uptodate = self.get_source(environment, name)
      File "/home/jeremie/miniconda3/lib/python3.7/site-packages/jinja2/loaders.py", line 232, in get_source
        pieces = split_template_path(template)
      File "/home/jeremie/miniconda3/lib/python3.7/site-packages/jinja2/loaders.py", line 31, in split_template_path
        raise TemplateNotFound(template)
    jinja2.exceptions.TemplateNotFound: ../ressources/r_notebook.template.html
```

to fix, need to fix template path in _rmarkdown.py_ like so
```python       
365: return env.get_template('~/miniconda3/lib/python3.7/site-packages/ipymd/ressources/r_notebook.template.html')
```

**Comment by grst** [comment]
Hi @jkobject, 

I do not support ipymd any more in favor of [jupytext](https://github.com/mwouts/jupytext). 
However, if you create a PR that fixes the issue, I'll merge it.

**Comment by jkobject** [comment]
Hey, 

Will jupytext allow me to run rmd scripts?

**Comment by grst** [comment]
yes, totally!
